### ISSUE TITLE
No deploy to sandbox option found

### ISSUE THREAD

**Issue by Yi-Zhang-IC** [noodlapp/noodl#26]
How to export code to a local folder and how to deploy to your sandbox?
<img width="301" alt="image" src="https://github.com/noodlapp/noodl/assets/74462273/d427de71-198f-432a-981f-b6a51ee9d40f">

**Comment by OscarMayReal** [comment]
I assume you are talking about the Noodl hosted sandbox deploys

you cannot deploy code to sandbox using the open source version of Noodl

if you want to deploy to sandbox you need to use the legacy, closed source version

**Comment by erictuvesson** [comment]
As @OscarMayReal said, there are some differences between the commercial version of Noodl and the open source version. Deploying is one of them where you only can deploy to folder.

If you are looking at how to host the files that are produced by the deploy to folder, I suggest you check with people on the Discord channel since there are many different ways.
